### PR TITLE
UI connection warning:

### LINKED ISSUE #971: Show warning if can't connect to api_url
When deploying an app if you don't update the `api_url` in your `pcconfig.py` currently the app doesn't work and you have to go in the Network tab to see the error. We should have a way to throw a UI warning when the backend isn't connected.

### PR DESCRIPTION
**Pull request by ElijahAhianyo**
This Pr adds a UI warning when server is unreachable
Screenshot 2023-05-31 at 3 34 45 PM

You also have the option of modifying the component that gets displayed.

```python

# Add state and page to the app.
app = pc.App(state=State, connect_error_component=pc.connection_banner(
    pc.box(
        pc.text(
            "cannot connect to server. This is edited",
            bg="black",
            color="white",
        ),
        textAlign="center",
    )
))
app.add_page(index)
app.compile()
```

To turn this feature/warning off, you can set the `check_connection` flag to False:

```python

# Add state and page to the app.
app = pc.App(state=State, check_connection=False)
app.add_page(index)
app.compile()
```
### All Submissions:

- [ ] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [ ] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

closes #971

### CODE REVIEW

**Review by masenf — COMMENTED** [review]
would it be possible to implement this as a component that we could add and style to fit our app? the current implementation seems kind of hard coded and fixed

File: pynecone/.templates/jinja/web/pages/index.js.jinja2 [hunk 1]
```diff
@@ -70,7 +71,21 @@ export default function Component() {
   {% endfor %}
 
   return (
+  <Fragment>
+      <Fragment>
+        {notConnected ? (
+          <Box sx={% raw %}{{"textAlign": "center"}}{% endraw %}>
```
Comment (picklelo) [inline pynecone/.templates/jinja/web/pages/index.js.jinja2:77]: I think we can define this as a Pynecone component - and allow the user to override it as an argument to `pc.App`

**Review by picklelo — COMMENTED** [review]
Awesome! I think we just need to update it so the warning is written in Pynecone so it can be customized

File: pynecone/.templates/web/utils/state.js [hunk 2]
```diff
@@ -193,9 +193,11 @@ export const connect = async (
   result,
   setResult,
   router,
-  transports
+  transports,
+  setNotConnected
 ) => {
   // Get backend URL object from the endpoint
+  console.log("event url", EVENTURL);
```
Comment (picklelo) [inline pynecone/.templates/web/utils/state.js:200]: leftover debug

File: pynecone/app.py [hunk 3]
```diff
@@ -65,6 +66,12 @@ class App(Base):
     # List of event handlers to trigger when a page loads.
     load_events: Dict[str, List[EventHandler]] = {}
 
+    # The component to render if there is a connection error to the server.
+    connect_error_component: Optional[Component] = None
+
+    # Whether to render component if server cant be reached.
```
Comment (picklelo) [inline pynecone/app.py:72]: Maybe we can combine this with the above? If it is set to `None` we don't check the connection since there's nothing to display

File: pynecone/compiler/compiler.py [hunk 4]
```diff
@@ -62,16 +67,20 @@ def _compile_theme(theme: dict) -> str:
...
 
     Args:
         component: The component to compile.
         state: The app state.
+        connect_error_component: The component to render on sever connection error.
 
     Returns:
         The compiled component.
     """
+    # breakpoint()
```
Comment (picklelo) [inline pynecone/compiler/compiler.py:83]: extra debug

**Review by picklelo — COMMENTED** [review]
nice! just a couple leftover statements to cleanup

File: pynecone/.templates/web/utils/state.js (hunk 2 above)
Comment (ElijahAhianyo) [reply pynecone/.templates/web/utils/state.js]: ah nice catch

File: pynecone/.templates/jinja/web/pages/index.js.jinja2 [hunk 5]
```diff
@@ -11,6 +11,7 @@
 export default function Component() {
   const [{{state_name}}, {{state_name|react_setter}}] = useState({{initial_state|json_dumps}})
   const [{{const.result}}, {{const.result|react_setter}}] = useState({{const.initial_result|json_dumps}})
+  const [notConnected, setNotConnected] = useState(false)
```
Comment (masenf) [inline pynecone/.templates/jinja/web/pages/index.js.jinja2:14]: Instead of capturing a bool here, this state could store the last connection error.

Then

```
connection_error = BaseVar("connectionError", type_="str", is_local=True)
```

And any page could reference this var

```python
pc.cond(
    connection_error != "",
    error_component(connection_error),
)
```

File: pynecone/.templates/web/utils/state.js [hunk 6]
```diff
@@ -207,6 +208,11 @@ export const connect = async (
   // Once the socket is open, hydrate the page.
   socket.current.on("connect", () => {
     updateState(state, setState, result, setResult, router, socket.current);
+    setNotConnected(false)
+  });
+
+  socket.current.on('connect_error', (error) => {
```
Comment (masenf) [inline pynecone/.templates/web/utils/state.js:214]: I think it would be nice to stash this `error` in the component state and then export a `BaseVar` that references the state value. Then the default connection error banner could render as a `pc.cond` on that var (and it could optionally render the actual error message).

With this approach, the page template wouldn't need special handling to render the error component, since the `connectionError` could be referenced in the compiled page.

**Review by masenf — CHANGES_REQUESTED** [review]
Having _less_ special case rendering logic in the jinja templates will increase maintainability and customization from the python side. Where possible, the client side state (not the State dict, but any other `useState` hook call) should be exposed to the pynecone compiler via `BaseVar` declarations that can be used like any other State var when constructing the frontend page.

File: pynecone/.templates/web/utils/state.js (hunk 6 above)
Comment (picklelo) [reply pynecone/.templates/web/utils/state.js:214]: Great idea, we will add this in a follow-up

**Review by picklelo — APPROVED** [review]
awesome
